string = input("введите строку:")
print(string[2])
print(string[-2])
print(string[:5])
print(string[0:-2])
print(string[2::2])
print(string[1::2])
print(string[-1::-1])
print(string[-1::-2])
print(len(string))